# 데이터처리프로그래밍- numpy 배열
### 2020/06/24 Keonwoo Park

In [1]:
import numpy as np

In [2]:
numbers = np.array(range(1,11), copy=True)

In [3]:
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
data_lists = [[1,2,3,4,5],[6,7,8,9,10]]
data_lists

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [6]:
arr = np.array((data_lists))
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
# 모든 값을 1로
ones = np.ones([2,4], dtype = np.float64)
# 데이터가 없기 때문에 데이터 타입을 줌
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
ones = np.ones([2,4],dtype=np.int64)
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [9]:
zeros = np.zeros([2,4], dtype=np.float64)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
empty = np.empty([2,4], dtype=np.float64)
empty

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
empty = np.empty([2,4], dtype=np.bool_)
empty

array([[False, False, False, False],
       [False, False, False, False]])

In [12]:
empty = np.empty([2,4], dtype="<U32")
empty

array([['', '', '', ''],
       ['', '', '', '']], dtype='<U32')

In [16]:
ones.shape

(2, 4)

In [17]:
ones.ndim

2

In [18]:
ones.dtype

dtype('int64')

In [19]:
# 단위 행렬 만들기
eye = np.eye(3)

In [20]:
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
eye = np.eye(3,3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
eye = np.eye(3,M=None,k=1)
eye

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [30]:
eye = np.eye(3,4)
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [32]:
eye = np.eye(3,4,k=1)
eye

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
# 일정 간격 배열 만들기
np_numbers = np.arange(2,5,0.25)
np_numbers

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 ,
       4.75])

In [38]:
np_inum = np_numbers.astype(np.int)
np_inum

array([2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

## 행렬 전환과 형태 변환하기

In [39]:
sap = np.array(["MMM","AFD","GSD","GDD","FDSF","SDFs","SDFSD","ZXCV"])
sap

array(['MMM', 'AFD', 'GSD', 'GDD', 'FDSF', 'SDFs', 'SDFSD', 'ZXCV'],
      dtype='<U5')

In [40]:
sap2d = sap.reshape(2,4)
sap2d

array([['MMM', 'AFD', 'GSD', 'GDD'],
       ['FDSF', 'SDFs', 'SDFSD', 'ZXCV']], dtype='<U5')

In [41]:
sap3d = sap.reshape(2, 2, 2)
sap3d

array([[['MMM', 'AFD'],
        ['GSD', 'GDD']],

       [['FDSF', 'SDFs'],
        ['SDFSD', 'ZXCV']]], dtype='<U5')

In [43]:
sap3d[0,1,0]

'GSD'

In [46]:
# 전치행렬 Transpose
sap4d = sap2d.T.copy()
sap4d

array([['MMM', 'FDSF'],
       ['AFD', 'SDFs'],
       ['GSD', 'SDFSD'],
       ['GDD', 'ZXCV']], dtype='<U5')

In [48]:
sap2d

array([['MMM', 'AFD', 'GSD', 'GDD'],
       ['FDSF', 'SDFs', 'SDFSD', 'ZXCV']], dtype='<U5')

In [50]:
sap3d.swapaxes(1,2)

array([[['MMM', 'GSD'],
        ['AFD', 'GDD']],

       [['FDSF', 'SDFSD'],
        ['SDFs', 'ZXCV']]], dtype='<U5')

In [55]:
# 0 번축 그대로 2 , 1 바꾸기
sap3d.transpose(1,2,0)

array([[['MMM', 'FDSF'],
        ['AFD', 'SDFs']],

       [['GSD', 'SDFSD'],
        ['GDD', 'ZXCV']]], dtype='<U5')

In [52]:
sap3d

array([[['MMM', 'AFD'],
        ['GSD', 'GDD']],

       [['FDSF', 'SDFs'],
        ['SDFSD', 'ZXCV']]], dtype='<U5')

# 인덱싱과 자르기

In [56]:
dirty = np.array([9,4,1,-0.1,-0.2,-0.001])
# 0보다 작은 값은 True
nt_dirty = dirty<0
nt_dirty

array([False, False, False,  True,  True,  True])

In [58]:
# 음수 값을 0으로 바꾼다.
dirty[nt_dirty]=0
dirty

array([9., 4., 1., 0., 0., 0.])

In [60]:
linear = np.arange(-1, 1.1, 0.2)
linear

array([-1.00000000e+00, -8.00000000e-01, -6.00000000e-01, -4.00000000e-01,
       -2.00000000e-01, -2.22044605e-16,  2.00000000e-01,  4.00000000e-01,
        6.00000000e-01,  8.00000000e-01,  1.00000000e+00])

In [61]:
(linear <= 0.5)&(linear >= -0.5)

array([False, False, False,  True,  True,  True,  True,  True, False,
       False, False])

In [62]:
sap = np.array(["MMM","AFD","GSD","GDD","FDSF","SDFs","SDFSD","ZXCV"])
sap

array(['MMM', 'AFD', 'GSD', 'GDD', 'FDSF', 'SDFs', 'SDFSD', 'ZXCV'],
      dtype='<U5')

In [65]:
sap2d = sap.reshape(2,4)
sap2d

array([['MMM', 'AFD', 'GSD', 'GDD'],
       ['FDSF', 'SDFs', 'SDFSD', 'ZXCV']], dtype='<U5')

In [72]:
# 각 위치의 값만 가져오기
sap[[1,2,-1]]

array(['AFD', 'GSD', 'ZXCV'], dtype='<U5')

In [74]:
# 같은 값을 뽑지만 형태가 다르다.
a=sap2d[:,[1]]
print(a.shape)
a

(2, 1)


array([['AFD'],
       ['SDFs']], dtype='<U5')

In [75]:
a = sap2d[:,1]
print(a.shape)
a

(2,)


array(['AFD', 'SDFs'], dtype='<U5')

# 브로드 캐스팅

In [76]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [77]:
b = np.arange(1,5)
b

array([1, 2, 3, 4])

In [78]:
a+b

array([1, 3, 5, 7])

In [80]:
a-b

array([-1, -1, -1, -1])

In [81]:
a*5

array([ 0,  5, 10, 15])

In [82]:
noise = np.eye(4)
noise

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [83]:
noise = np.eye(4) + 0.01 * np.ones((4,))
noise

array([[1.01, 0.01, 0.01, 0.01],
       [0.01, 1.01, 0.01, 0.01],
       [0.01, 0.01, 1.01, 0.01],
       [0.01, 0.01, 0.01, 1.01]])

In [84]:
noise = np.eye(4) + 0.01 * np.random.random([4,4])
noise

array([[1.00923480e+00, 3.48819705e-03, 3.35868570e-03, 8.17373761e-05],
       [3.92302852e-03, 1.00678120e+00, 6.27425259e-03, 7.45908448e-03],
       [1.93328443e-03, 9.79309494e-03, 1.00729353e+00, 6.17434269e-03],
       [8.16074670e-03, 8.79752381e-03, 9.37037621e-03, 1.00398631e+00]])

In [85]:
noise.round(2)

array([[1.01, 0.  , 0.  , 0.  ],
       [0.  , 1.01, 0.01, 0.01],
       [0.  , 0.01, 1.01, 0.01],
       [0.01, 0.01, 0.01, 1.  ]])

# 유니버셜 함수

In [88]:
stocks = np.array([140.49, 0.97, 40.68, 41.53, 55.7, 57.21, 98.2, 109.96, 111.47, 35.71, 36.27, 87.85, 89.11,
                  30.22, 30.91, 20.1])
stocks

array([140.49,   0.97,  40.68,  41.53,  55.7 ,  57.21,  98.2 , 109.96,
       111.47,  35.71,  36.27,  87.85,  89.11,  30.22,  30.91,  20.1 ])

In [95]:
stocks = stocks.reshape(8, 2 ).T

In [96]:
tall = np.greater(stocks[0], stocks[1])
tall

array([ True, False, False, False,  True, False,  True,  True])

In [98]:
stocks[1,0] = np.nan
stocks

array([[140.49,    nan,  55.7 ,  98.2 , 111.47,  36.27,  89.11,  30.91],
       [   nan,  41.53,  57.21, 109.96,  35.71,  87.85,  30.22,  20.1 ]])

In [100]:
np.isnan(stocks)

array([[False,  True, False, False, False, False, False, False],
       [ True, False, False, False, False, False, False, False]])

In [101]:
stocks[np.isnan(stocks)] = 0
stocks

array([[140.49,   0.  ,  55.7 ,  98.2 , 111.47,  36.27,  89.11,  30.91],
       [  0.  ,  41.53,  57.21, 109.96,  35.71,  87.85,  30.22,  20.1 ]])

In [ ]:
# 하나의 함수가 모든 값에 적용 되는 경우를 유니버셜함수라고함

# 조건부 함수 이해하기

In [102]:
stocks

array([[140.49,   0.  ,  55.7 ,  98.2 , 111.47,  36.27,  89.11,  30.91],
       [  0.  ,  41.53,  57.21, 109.96,  35.71,  87.85,  30.22,  20.1 ]])

In [ ]:
# 주식의 가격이 눈에 띄게 변화 했는지를 

In [103]:
changes = np.where(np.abs(stocks[1]- stocks[0])> 1.00,stocks[1]-stocks[0],0)

In [104]:
changes

array([-140.49,   41.53,    1.51,   11.76,  -75.76,   51.58,  -58.89,
        -10.81])